import { IMathOperations } from './interfaces';

export const buttonsLibrary = [
  { value: 'C', type: 'clear' },
  { value: '\u221A', type: 'operation', priority: 3 },
  { value: '%', type: 'operation', priority: 2 },
  { value: '/', type: 'operation', priority: 2 },
  { value: '1', type: 'number' },
  { value: '2', type: 'number' },
  { value: '3', type: 'number' },
  { value: '*', type: 'operation', priority: 2 },
  { value: '4', type: 'number' },
  { value: '5', type: 'number' },
  { value: '6', type: 'number' },
  { value: '-', type: 'operation', priority: 1 },
  { value: '7', type: 'number' },
  { value: '8', type: 'number' },
  { value: '9', type: 'number' },
  { value: '+', type: 'operation', priority: 1 },
  { value: '(', type: 'braket' },
  { value: ')', type: 'braket' },
  { value: '0', type: 'number' },
  { value: '.', type: 'devider' },
  { value: '=', type: 'exec' },
];

export const mathOperations: IMathOperations = {
  '+': (val1, val2) => val1 + val2,
  '-': (val1, val2) => val1 - val2,
  '*': (val1, val2) => val1 * val2,
  '/': (val1, val2) => val1 / val2,
  '\u221A': (val1) => Math.sqrt(val1),
  '%': (val1, val2) => (val1 * val2) / 100,
};

export const keyMapper: Record<string, string> = {
  '1': '1',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5',
  '6': '6',
  '7': '7',
  '8': '8',
  '9': '9',
  '0': '0',
  '.': '.',
  '=': '=',
  Enter: '=',
  '+': '+',
  '-': '-',
  '*': '*',
  '/': '/',
  '%': '%',
  Escape: 'C',
  Clear: 'C',
  Backspace: 'C',
  '^': '\u221A',
  '(': '(',
  ')': ')',
};
